In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os

culture_root = os.environ["CULTURE_ROOT"]

# Chinese

In [5]:
import json
import pandas as pd
# xinhua
df_zh_xinhua_idioms = pd.DataFrame().from_records(json.load(open(culture_root + "/culture/data/chinese-xinhua/data/idiom.json", "r")))
df_zh_xinhua_xiehouyu = pd.DataFrame().from_records(json.load(open(culture_root + "/culture/data/chinese-xinhua/data/xiehouyu.json", "r")))
df_zh_xinhua_idioms

,derivation,example,explanation,pinyin,word,abbreviation
0,语出《法华经·法师功德品》下至阿鼻地狱。”,但也有少数意志薄弱的……逐步上当，终至堕入～。★《上饶集中营·炼狱杂记》,阿鼻梵语的译音，意译为无间”，即痛苦无有间断之意。常用来比喻黑暗的社会和严酷的牢狱。又比喻无...,ā bí dì yù,阿鼻地狱,abdy
1,三国·魏·曹操《整齐风俗令》阿党比周，先圣所疾也。”,《论语·卫灵公》众恶之，必察焉；众好之，必察焉”何晏集解引三国魏王肃曰或众～，或其人特立不群...,指相互勾结，相互偏袒，结党营私。,ē dǎng bǐ zhōu,阿党比周,edbz
2,《汉书·诸葛丰传》今以四海之大，曾无伏节死谊之臣，率尽苟合取容，阿党相为，念私门之利，忘国家...,无,阿党偏袒、偏私一方。为了谋求私利相互偏袒、包庇。,ē dǎng xiāng wéi,阿党相为,edxw
3,鲁迅《我们要批评家》然而新的批评家不开口，类似批评家之流便趁势一笔抹杀‘阿狗阿猫’。”,无,旧时人们常用的小名。引申为任何轻贱的，不值得重视的人或著作。,ā gǒu ā māo,阿狗阿猫,agam
4,见阿家阿翁”。,既然如此，你我两个，便学个不痴不聋的～。★《儿女英雄传》二三回,阿名词的前缀。姑丈夫的母亲。翁丈夫的父亲。指公公婆婆。,ā gū ā wēng,阿姑阿翁,agaw
...,...,...,...,...,...,...
30890,清·李宝嘉《文明小史》第四十四回我们做一天和尚撞一天钟，只要不像从前那位老中堂，摆在面上被人...,敷衍了事，得过且过，～。★毛泽东《反对自由主义》,俗语。过一天算一天，凑合着混日子。比喻遇事敷衍，得过且过。也有无可奈何，勉強从事的意思。,zuò yī tiān hé shàng zhuàng yī tiān zhōng,做一天和尚撞一天钟,zythszytz
30891,宋·释悟明《联灯会要·重显禅师》却顾侍者云‘适来有人看方丈么？’侍者云‘有。’师云‘作贼人心...,这个毛病，起先人家还不知道，这又是他们～弄穿的。★清·吴趼人《二十年目睹之怪现状》第六十回,虚怕。指做了坏事怕人知道，心里老是不安。,zuò zéi xīn xū,做贼心虚,zzxx
30892,语出《醒世恒言·卖油郎独占花魁》那些有势有力的不肯出钱，专要讨人便宜。及至肯出几两银子的，女...,[蒋淑真]梳个纵鬓头儿，着件叩身衫子，～，乔模乔样。★《醒世通言蒋淑真刎颈鸳鸯会》,装模作样，故意做出一种姿态。,zuò zhāng zuò shì,做张做势,zzzs
30893,语出《醒世恒言·卖油郎独占花魁》那些有势有力的不肯出钱，专要讨人便宜。及至肯出几两银子的，女...,沈琼枝看那两个妇人时，一个二十六七岁光景，一个十七八岁，乔素打扮，～的。★清·吴敬梓《儒林外...,犹言装模作样，装腔作势。,zuò zhāng zuò zhì,做张做致,zzzz
30894,《醒世恒言·卖油郎独占花魁》那些有势有力的不肯出钱，专要讨人便宜。及至肯出几两银子的，女儿又...,[阮小七]提着双拳说道我老爷在此吃几杯酒儿，干你鸟事！～要来拿我！”★《水浒传》第一回,犹言装模作样，装腔作势。,zuò zhāng zuò zhì,做张做智,zzzz

In [6]:
df_zh_xinhua_xiehouyu

                         riddle       answer
0                   做砖的坯子、插刀的鞘子         框框套套
1                       做贼碰上劫路人   坏到一块了；冤家路窄
2                        做贼的说梦话           想偷
3                       做贼的不用化装         贼眉贼眼
4                         做贼盗黄连         自讨苦吃
...                         ...          ...
14027                 阿拉伯数字8字分家     零比零（O：O）
14028                     阿公吃黄连        苦也（爷）
14029  阿二（民间传说中的呆头呆脑、自作聪明的人）炒年糕  费力不讨好；费劲不落好
14030                     阿斗的江山           白送
14031                     阿斗当皇帝         软弱无能

[14032 rows x 2 columns]

In [7]:
import pandas as pd

# path to your txt file
file_path = culture_root + "/culture/data/chengyu_data/chengyu_definition.txt"

# read the file line by line
rows = []
with open(file_path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        # split only on the first comma
        idiom, sentence = line.split(",", 1)
        rows.append({
            "idiom": idiom,
            "sentence": sentence
        })

# create DataFrame
df = pd.DataFrame(rows)

df

     idiom                                    sentence
0     不学无术         学：学问；术：技能。原指没有学问因而没有办法。现指没有学问，没有本领。
1     安富尊荣  安：安逸；富：富有；尊：尊贵；荣：荣耀。安定富足，尊贵荣华。也指安于富裕安乐的生活。
2     有勇无谋           只有勇气，没有计谋。指做事或打仗只是猛打猛冲，缺乏计划，不讲策略。
3     故作高深      本来并不高深，故意装出高深的样子。多指文章故意用些艰深词语，掩饰内容的浅薄。
4     忍俊不禁                    忍俊：含笑；不禁：无法控制自己。指忍不住要发笑。
...    ...                                         ...
7371  与世无争               不跟社会上的人发生争执。这是一种消极的回避矛盾的处世态度。
7372  万夫不当        夫：人。当：抵挡。上万个人也抵挡不住。形容人非常勇猛。亦作“万夫莫当”。
7373  外强中干                           干：枯竭。形容外表强壮，内里空虚。
7374  头角峥嵘       头角：比喻青年人显露出来的才华；峥嵘：特出的样子。形容年轻有为，才华出众。
7375  不容分说                           分说：辩白，解说。不容人分辩解释。

[7376 rows x 2 columns]